### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Lolopeze** [Seeed-Studio/seeed-ardupy-mlx9064x#1]
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\z440\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "c:\users\z440\appdata\local\programs\python\python38\lib\site-packages\aip\build.py", line 492, in run
    raise Exception(print('compile error'))
Exception: None

**Comment by Lolopeze** [comment]
My bad. Sorry.
